<?php
/**
 * @file primo_search_block.module
 * TODO: Enter file description here.
 */



/**
 * Implements hook_block_info().
 */
function primo_search_block_block_info() {
  $blocks = array(
    'primo_search_block' => array(
        'info' => t('Primo Search Block'),
      ),
    );
  return $blocks;
}

/**
 * Builds the select element for the scopes list.
 * @param  array  $scopes Associative array of label to value
 * @return string         Markup to be added to the form.
 */
function primo_search_block_scopes_select(array $scopes){
  $markup = '';
  foreach ($scopes as $label => $value) {
    $markup .= '<option value="'. $value.'">'.$label.'</option>';
  }

  $markup = '<select name="search_scope">'.$markup.'</select>';
  return $markup;
}

/**
 * Implements hook_block_view().
 */
function primo_search_block_block_view($delta = '') {
  $block = array();
  switch ($delta) {
    case 'primo_search_block':

      $searchScopes = (array) variable_get('primo_search_search_scope', array(

        ));
      $modulePath = drupal_get_path('module', 'primo_search_block');
      $block['subject'] = t(variable_get('primo_search_block_title', 'Primo Search'));
      $block['content'] = array(
        'form' => array(
          '#type'=> 'markup',
          '#markup'=>
          '
            <form name="searchForm" role="search" method="get" action="http://'. variable_get('primo_search_block_url', 'example.com:1701') .  /* <PRIMO_URL:PORT> */  '/primo_library/libweb/action/dlSearch.do" enctype="application/x-www-form-urlencoded; charset=utf-8" id="simple" class="primo-search" target="_self"  onsubmit="searchPrimo()">
            <input name="institution" value="'.variable_get('primo_search_block_institution_code', 'EXL') . /*<INSTITUTION_CODE>*/ '" type="hidden">
            <input name="vid" value="'. variable_get('primo_search_block_view_code', 'EXL'). /*<VIEW_CODE>*/'" type="hidden">
            <input name="group" value="GUEST" type="hidden">
            <input name="onCampus" value="true" type="hidden">
            <input name="displayMode" value="full" type="hidden">
            <input type="hidden" id="primoQuery" name="query" />
            <input type="text" size="25" id="primoQueryTemp" value="" placeholder="Search..." name="queryTemp" onkeypress="return searchPrimoEvent(event)" />
            '. 
              primo_search_block_scopes_select($searchScopes)
            .'
            <input id="go" type="button" value="Search" title="Search"  onclick="searchPrimo()" alt="Search">
            </form>
          ',
          '#attached' => array(
            'js' => array( $modulePath . '/js/primo_search_block.min.js'),
            'css' => array($modulePath . '/css/primo_search_block.css'),
            ),
          ),

        );
    break;
  }
  return $block;
}

/**
 * Implements hook_block_configure().
 */
function primo_search_block_block_configure($delta = '') {
  $form = array();
   if ($delta == 'primo_search_block') {
    $form['primo_search_block_scope_json'] = array(
      '#type' => 'textfield',
      '#title' => t('Search scopes'),
      '#default_value' => variable_get('primo_search_block_scope_json'
        ,'{"Library Catalogs + Articles":"everything_scope","Library Catalogs":"nu_scope","Law Library Catalog":"nu_law","Course Reserves":"nu_cr"}'
        ),
      '#required' => True,
      '#size'=> 200,
      '#maxlength'=> 999,
      '#element_validate' => array('primo_search_block_scope_json_validate'),
      );

    $form['primo_search_block_institution_code']= array(
      '#type' => 'textfield',
      '#title' => t('Institution Code'),
      '#default_value'=> variable_get('primo_search_block_institution_code', 'NEU'),
      '#required' => True
      );
    
    $form['primo_search_block_url']= array(
      '#type' => 'textfield',
      '#title' => t('Primo\'s Url and Port'),
      '#default_value' => variable_get('primo_search_block_url', 'onesearch.northeastern.edu:1701'),
      '#required' => True,
      );
    $form['primo_search_block_view_code'] = array(
      '#type' => 'textfield',
      '#title' => t('View code.'),
      '#default_value'=> variable_get('primo_search_block_view_code', 'NU'),
      '#required' => True,
      );
   }
  return $form;
}

/**
 * Form search scope validation funtion.
 * @param  array $element the returne form element.
 *
 * @todo Fix this!
 */
function primo_search_block_scope_json_validate($element, &$form_state, $form){
  $test = @json_decode($element['#value']);
  if ($test === null && json_last_error() !== JSON_ERROR_NONE) {
    form_set_error('primo_search_search_scope_json', t('Primo search scopes must be vaild JSON.'));
  }
}



/**
 * Implements hook_block_save().
 */
function primo_search_block_block_save($delta = '', $edit = array()) {
  if ($delta == 'primo_search_block'){
    variable_set('primo_search_block_scope_json', $edit['primo_search_block_scope_json']);
    variable_set('primo_search_block_scope_array', json_decode($edit['primo_search_block_scope_json'],True));
    variable_set('primo_search_block_view_code', $edit['primo_search_block_view_code']);
    variable_set('primo_search_block_institution_code', $edit['primo_search_block_institution_code']);
    variable_set('primo_search_block_url', $edit['primo_search_block_url']);
  }

}
