<?php
/**
 * @file primo_search_block.module
 * TODO: Enter file description here.
 */

/**
 * Implements hook_menu().
 */
function primo_search_block_menu() { 
  // This is the minimum information you can provide for a menu item.
  $items['primo_search_block'] = array(
    'title' => 'TODO: Enter menu item title',
    'page callback' => 'TODO: Enter callback function',
    'access arguments' => array('TODO: Enter user permissions'),
  );
  // This is a menu item for a form.
  $items['primo_search_block/admin'] = array(
    'title' => 'TODO: Enter menu item title',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('primo_search_block_form'),
    'access arguments' => array('TODO: Enter user permissions'),
  );
  // More complex menu item.
  $items['primo_search_block/foo'] = array(
    'title' => 'TODO: Enter menu item title',
    'description' => 'TODO: Enter description',
    'page callback' => 'TODO: Enter callback function',
    'page arguments' => array(), // An array of arguments to pass to the page callback function. Integer values pass the corresponding URL component.
    'access callback' => '', // defaults to user_access()
    'access arguments' => array('TODO: Enter user permissions'),
    'weight' => 0,
    'type' => MENU_NORMAL_ITEM, // One of MENU_NORMAL_ITEM / MENU_CALLBACK / MENU_SUGGESTED_ITEM / MENU_LOCAL_TASK / MENU_DEFAULT_LOCAL_TASK
    'file' => 'primo_search_block.admin.inc',
    'menu_name' => '', // Menu to place this item in.
    'title callback' => '', // Function to generate the title, defaults to t(). 
    'title arguments' => array(), // Arguments to send to t() or your custom callback. 
  );
  // OPTIONAL: Fill in additional menu items

  return $items;
}
